### ISSUE TITLE
Undefined indexes on rasa-router

### ISSUE THREAD

**Issue by versedpro** [chatwoot/rasa-agent-bot-demo#1]
Hello

I have followed your guide and when I sent message from web widget to chatwoot, the bot wasn't working properly.
My whole error log of running rasa (rasa-router/index.php) like below:
```
[Mon Aug 31 16:59:41 2020] PHP Notice:  Undefined index: message_type in /home/chatwoot/chatwoot/rasa-router/index.php on line 10
[Mon Aug 31 16:59:41 2020] PHP Notice:  Undefined index: content in /home/chatwoot/chatwoot/rasa-router/index.php on line 11
[Mon Aug 31 16:59:41 2020] PHP Notice:  Undefined index: conversation in /home/chatwoot/chatwoot/rasa-router/index.php on line 12
[Mon Aug 31 16:59:41 2020] PHP Notice:  Undefined index: contact in /home/chatwoot/chatwoot/rasa-router/index.php on line 13
[Mon Aug 31 16:59:41 2020] PHP Notice:  Undefined index: account in /home/chatwoot/chatwoot/rasa-router/index.php on line 14
[Mon Aug 31 16:59:41 2020] message_type: 
[Mon Aug 31 16:59:41 2020] 127.0.0.1:48416 [200]: /
```
I think the params posted from widget were not correct.
Could you check and help me please?

Thanks so much.

**Comment by sojan-official** [comment]
earlier we used to send data as form data in chatwoot app, this had been changed to json and that's what broke the PHP script. 

https://github.com/chatwoot/rasa-agent-bot-demo/commit/5dafe56d0c7de33c4fddfc997572c360c9503185 fixes this
