### ISSUE TITLE
No route matches [GET] "/widget_tests"

### ISSUE THREAD

**Issue by yYang365** [chatwoot/rasa-agent-bot-demo#10]
When I try to access the http://localhost:3000/widget_tests , I will get The page you were looking for doesn't exist.
log:
```
[2021-06-29T05:53:00.809604 #1] INFO -- : [fe6e6a2f-22a1-45d4-9c2d-28716c6a952f] Started GET "/widget_tests" for 172.28.0.1 at 2021-06-29 05:53:00 +0000
F, [2021-06-29T05:53:00.811262 #1] FATAL -- : [fe6e6a2f-22a1-45d4-9c2d-28716c6a952f]
[fe6e6a2f-22a1-45d4-9c2d-28716c6a952f] ActionController::RoutingError (No route matches [GET] "/widget_tests"):
```

**Comment by yYang365** [comment]
I search key word "widget_tests" in repository chatwoot/chatwoot , I got:

### spec/controllers/widget_tests_controller_spec.rb

```
require 'rails_helper'

describe '/widget_tests', type: :request do
  before do
    create(:channel_widget)
  end

  describe 'GET /widget_tests' do
    it 'renders the page correctly' do
      get widget_tests_url
```
##### Ruby Showing the top two matches Last indexed on Apr 4

### config/routes.rb

```
  get '/swagger', to: 'swagger#respond'

  # ----------------------------------------------------------------------
  # Routes for testing
  resources :widget_tests, only: [:index] unless Rails.env.production?
end
```
##### Ruby Showing the top match Last indexed 14 days ago

I think the route (/widget_tests) should exist.

**Comment by sojan-official** [comment]
ensure that you are running the rails app in a development environment. Widget tests URL end point isn't available in production environments
