### ISSUE TITLE
Create the bot agent

### ISSUE THREAD

**Issue by converso-chat** [chatwoot/rasa-agent-bot-demo#2]
Do I necessarily need to create the bot agent from the command line? If creating the agent on the panel, shouldn't obtaining the key work? I installed in Heroku and I am not able to create the agent

Thanks

**Comment by SmartManoj** [comment]
Did you get any errors?

**Comment by ArunYokesh1** [comment]
After running Chatwoot in heroku, when we try to run below command
`bot = AgentBot.create!(name: "Rasa Bot", outgoing_url: "http://localhost:8000")`

gives below failure message
`/app/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in 'rescue in new_client': could not connect to server: Connection refused (ActiveRecord::ConnectionNotEstablished)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
/app/vendor/bundle/ruby/3.0.0/gems/pg-1.2.3/lib/pg.rb:58:in 'initialize': could not connect to server: Connection refused (PG::ConnectionBad)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?`
        
Could you help us resolving this issue.

**Comment by SmartManoj** [comment]
@ArunYokesh1 Is PostgreSQL running?

**Comment by ArunYokesh1** [comment]
@SmartManoj , Postgres is running, but its not available in "localhost", as it is in heroku, its running in "xxxxxxxxxxxx.eu-west-1.compute.amazonaws.com"

**Comment by SmartManoj** [comment]
Use https://ngrok.com or host the bot.

**Comment by ArunYokesh1** [comment]
ok, Have installed the chatwoot in standalone ubuntu server. running this router as well. I am able to see messages from user (customer typing in chatwoot widget) to chatwoot, but the same message is not reaching rasa. At the same time, message from rasa is reaching chatwoot and user. How make the user/customer typing reaches chatwoot and rasa.

How /Where can I see the AgentBot created from Terminal as instructed in the readme file ?

**Comment by SmartManoj** [comment]
AgentBot created?

**Comment by ArunYokesh1** [comment]
Agent Bot, created. This is in Standalone Ubuntu Server. Have dropped the idea of heroku deployment for the same.

> AgentBot created?

**Comment by sojan-official** [comment]
Hi folks, this code in this repo isn't exactly ideal for production.  If you are still having issues creating AgentBots please feel free to add it to our main repo https://github.com/chatwoot/chatwoot
