### ISSUE TITLE
404 when testing 

### ISSUE THREAD

**Issue by SmartManoj** [chatwoot/rasa-agent-bot-demo#4]
http://localhost:3000/widget_tests

**Comment by pranavrajs** [comment]
@SmartManoj Please add more info to issues, closing it as there is no other information available to debug this issue.

**Comment by SmartManoj** [comment]
In the readme, it states that,

```
if you are on your local machine, you can access the widget through the test page
http://localhost:3000/widget_tests
```

**Comment by SmartManoj** [comment]
Is it just an example link where we place the widgest?

**Comment by pranavrajs** [comment]
@SmartManoj It is only available in development mode while running Chatwoot Server if that helps.
