### ISSUE TITLE
chatwood_dev database doesn't exist

### ISSUE THREAD

**Issue by ktyborowski** [chatwoot/rasa-agent-bot-demo#5]
After following the linux VM installation of chatwoot and running 
`bot = AgentBot.create!(name: "Rasa Bot", outgoing_url: "http://localhost:8000")`
in the rails console I'm getting an error message from postgres that the `chatwoot_dev` database doesn't exist. Any help to resolve this issue would be appreciated.

**Comment by pranavrajs** [comment]
@pixpack Please run `RAILS_ENV=production bundle exec rails c` instead of `rails c`. Please feel free to reopen the issue if it is still an issue.
