### ISSUE TITLE
Bot Doesn't respond

### ISSUE THREAD

**Issue by LewisBrowne** [chatwoot/rasa-agent-bot-demo#6]
Hi guys, 

is there any chance you could update your documentation to make the Rasa integration work when on production?

I have tried with and without a docker stack on our production server and the bot just never seems to respond. Rasa
looks to be running fine along with the rasa-router. Its almost like Chatwoot isn't forwarding to the router correctly but i cannot see why, please advise!

Thanks,
Lewis

**Comment by Gregory-Hepicloud** [comment]
Same issue here did you find fix ?

**Comment by KartikeyaRokde** [comment]
Same issue, did anyone find a fix? @Chatwoot team, can anyone please help here?

**Comment by amitchavan90** [comment]
Same issue, we tried changing `outgoing_url` directly from DB, and surprisingly Chatwoot called those urls, but I don't know what problem it has to call rasa-router script url (i`.e. localhost:8000`).

**Comment by amitchavan90** [comment]
Found the solution:
there seems to be some disconnect for localhost:8000 (not sure why its not accepting request from chatwoot). I deployed the same script to another instance serving over apache server on port 80, and it worked fine. 

P.S. curl request localhost:8000 from same system worked fine, but chatwoot still find some challenges to push the messages.

**Comment by sojan-official** [comment]
I have added https://github.com/chatwoot/implementation-examples/issues/7 to track adding documentation for an agent bot production deployment.
