### ISSUE TITLE
 Validation failed: Inbox can't be blank, Inbox must exist, Account must exist

### ISSUE THREAD

**Issue by jeovajireh** [chatwoot/rasa-agent-bot-demo#7]
Should this command be typed that way? The same is producing this error below, I tried to put the name of my inbox and the id, but it didn't work.

AgentBotInbox.create!(inbox: Inbox.first, agent_bot: bot)

Error:

ActiveRecord::RecordInvalid: Validation failed: Inbox can't be blank, Inbox must exist, Account must exist

Thanks

**Comment by sujanpgowda** [comment]
@viapratica We came across same issue. Could you proceed further from this step? Its a localhost installation on ubuntu wsl

**Comment by jeovajireh** [comment]
> @viapratica We came across same issue. Could you proceed further from this step? Its a localhost installation on ubuntu wsl

Friend, I abandoned the project! I needed something fast and I found the way to integrate the rasa to the inbox very complicated. My idea was to have a service bot for each WhatsApp inbox using the Twilio channel, but I saw that replicating this for different clients would not be an easy task.

Ubuntu 18 in VPS

**Comment by sojan-official** [comment]
@sujanpgowda `Inbox.first` is RoR syntax to return the first inbox object in the system. So before running the command ensure that you have an inbox in your chatwoot installation 

You can refer to: https://www.youtube.com/watch?v=KE4nKgepO_k

**Comment by murtuzaalisurti** [comment]
> @sujanpgowda `Inbox.first` is RoR syntax to return the first inbox object in the system. So before running the command ensure that you have an inbox in your chatwoot installation
> 
> You can refer to: https://www.youtube.com/watch?v=KE4nKgepO_k

how do you create a local inbox after installing chatwoot? it is not mentioned in the video?

**Comment by sojan-official** [comment]
@murtuzaalisurti You can log in to chatwoot and create an Inbox from the UI. or if you run the rails seeding command ie 
`rails db:chatwoot_prepare` , it will create an inbox for you.

**Comment by murtuzaalisurti** [comment]
> @murtuzaalisurti You can log in to chatwoot and create an Inbox from the UI. or if you run the rails seeding command ie `rails db:chatwoot_prepare` , it will create an inbox for you.

the inbox is created now but the rasa bot isn't responding...
![Screenshot (119)](https://user-images.githubusercontent.com/68743212/145777933-899c89a8-882b-4f13-8750-e03397ef0f32.png)

**Comment by sujanpgowda** [comment]
@sojan-official  @murtuzaalisurti   Same here, the chatwoot installation has an option for  dialogflow application only, Isn't there an option for rasa?  I have connected the chat widget to my wordpress installation, but rasa doesn't respond.

**Comment by sojan-official** [comment]
@sujanpgowda  tracking the request over https://github.com/chatwoot/chatwoot/issues/3597
